FROM node
WORKDIR /app
# ====
ARG CACHEBUST=1
RUN git clone https://github.com/Endibra90/apisanti.git . && \
    npm install
# ====
ENV MYDBHOST=db
ENV MYDATABASE=laravel
ENV MYUSER=root
ENV MYPASSWORD=
ENTRYPOINT [ "node", "appapi.js" ]
# docker-compose necesita saber que puerta está dando servicio
# a la api
EXPOSE 7000
